### ISSUE TITLE
Campaign ID not being filled in spreadsheet

### ISSUE THREAD

**Issue by gcmartinelli** [fczuardi/gsheetsbot#19]
Bot is not filling the campaign_id field when pushing new  deal to gsheets.

<img width="239" alt="deal" src="https://cloud.githubusercontent.com/assets/1650735/20482457/e3806fca-afd3-11e6-8f43-cec3e76269a9.PNG">

**Comment by fczuardi** [comment]
this happens when the user haven't navigated to the mission folder first, for example: if the user just typed /indicar

Do you know if that was the case?

We could add an extra config variable to setup a default campaing for when the user is submitting school forms from outside any specific campaing folder

**Comment by gcmartinelli** [comment]
Exactly the case. Maybe we should remove the message where the bot tells the user he can use /indicar to register a new school (he will only be  able to do that by navigating to the campaign menu).

**Comment by fczuardi** [comment]
after the fix of #10 it will be better to remove the text with /indicar command because it will be available as a button
